package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u201/12322/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Sunday, December 16, 2018 12:15:06 AM MST
*/

public interface TAG_POLICIES
{

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
  public static final int value = (int)(2L);
}
