package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u201/12322/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Sunday, December 16, 2018 12:15:07 AM MST
*/

public interface THREAD_POLICY_ID
{

  /**
	 * The value representing THREAD_POLICY_ID.
	 */
  public static final int value = (int)(16L);
}
